import random
import string
from typing import *
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from PySide6.QtGui import *

def randstring():
    text = ""
    for _ in range(random.randint(8,35)):
        text += random.choice(string.printable)
    return text

class Tab2(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.hlayout = QHBoxLayout()
        self.setLayout(self.hlayout)
        self.gridLayout = QGridLayout()
        self.hlayout.addLayout(self.gridLayout)
        self.groupBox = QGroupBox("Buttons", self)
        self.verticalLayout_3 = QVBoxLayout()
        self.groupBox.setLayout(self.verticalLayout_3)
        self.pushButton = QPushButton("Push Button", self)
        self.verticalLayout_3.addWidget(self.pushButton)
        self.radioButton = QRadioButton("Radio Button",self)
        self.verticalLayout_3.addWidget(self.radioButton)
        self.checkBox = QCheckBox("Check Box", self)
        self.verticalLayout_3.addWidget(self.checkBox)
        self.commandLinkButton = QCommandLinkButton("Command Link",self)
        self.verticalLayout_3.addWidget(self.commandLinkButton)
        self.toolButton = QToolButton(self)
        self.toolButton.setText("ToolButton")
        self.verticalLayout_3.addWidget(self.toolButton)
        self.buttonBox = QDialogButtonBox(self)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.toolBox = QToolBox(self)
        self.page = QWidget()
        self.verticalLayout_4 = QVBoxLayout()
        self.page.setLayout(self.verticalLayout_4)
        self.lineEdit = QLineEdit(self.page)
        self.page.setGeometry(QRect(0, 0, 260, 197))
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.timeEdit = QTimeEdit(self.page)
        self.verticalLayout_4.addWidget(self.timeEdit)
        self.fontComboBox = QFontComboBox(self.page)
        self.verticalLayout_4.addWidget(self.fontComboBox)
        self.comboBox = QComboBox(self.page)
        self.verticalLayout_4.addWidget(self.comboBox)
        self.spinBox = QSpinBox(self.page)
        self.verticalLayout_4.addWidget(self.spinBox)
        self.doubleSpinBox = QDoubleSpinBox(self.page)
        self.verticalLayout_4.addWidget(self.doubleSpinBox)
        self.toolBox.addItem(self.page, u"Page 1")
        self.page_2 = QWidget()
        self.page_2.setGeometry(QRect(0, -25, 243, 222))
        self.verticalLayout_7 = QVBoxLayout()
        self.page_2.setLayout(self.verticalLayout_7)
        self.textEdit = QTextEdit(self.page_2)
        self.verticalLayout_7.addWidget(self.textEdit)
        self.textBrowser = QTextBrowser(self.page_2)
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.dial = QDial(self.page_2)
        self.verticalLayout_7.addWidget(self.dial)
        self.toolBox.addItem(self.page_2, u"Page 2")
        self.gridLayout.addWidget(self.toolBox, 1, 1, 1, 1)
        self.scrollArea = QScrollArea(self)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -46, 330, 285))
        self.verticalLayout_6 = QVBoxLayout()
        self.scrollAreaWidgetContents.setLayout(self.verticalLayout_6)
        self.plainTextEdit = QPlainTextEdit(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.plainTextEdit)
        self.calendarWidget = QCalendarWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.calendarWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.stackedWidget_2 = QStackedWidget(self)
        self.page_5 = QWidget()
        self.horizontalLayout = QHBoxLayout()
        self.page_5.setLayout(self.horizontalLayout)
        self.line = QFrame(self.page_5)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout.addWidget(self.line)
        self.verticalSlider = QSlider(self.page_5)
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.horizontalLayout.addWidget(self.verticalSlider)
        self.lcdNumber = QLCDNumber(self.page_5)
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.verticalScrollBar = QScrollBar(self.page_5)
        self.verticalScrollBar.setOrientation(Qt.Vertical)
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.stackedWidget_2.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.verticalLayout_5 = QVBoxLayout()
        self.page_6.setLayout(self.verticalLayout_5)
        self.horizontalScrollBar = QScrollBar(self.page_6)
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.verticalLayout_5.addWidget(self.horizontalScrollBar)
        self.horizontalSlider = QSlider(self.page_6)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.verticalLayout_5.addWidget(self.horizontalSlider)
        self.line_2 = QFrame(self.page_6)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.verticalLayout_5.addWidget(self.line_2)
        self.progressBar = QProgressBar(self.page_6)
        self.progressBar.setValue(24)
        self.verticalLayout_5.addWidget(self.progressBar)
        self.keySequenceEdit = QKeySequenceEdit(self.page_6)
        self.verticalLayout_5.addWidget(self.keySequenceEdit)
        self.stackedWidget_2.addWidget(self.page_6)
        self.gridLayout.addWidget(self.stackedWidget_2, 1, 0, 1, 1)
        self.dockWidget = QDockWidget(self)
        self.hlayout.addWidget(self.dockWidget)
        self.dockWidgetContents = QWidget()
        self.verticalLayout_2 = QVBoxLayout()
        self.dockWidgetContents.setLayout(self.verticalLayout_2)
        self.listWidget = QListWidget(self.dockWidgetContents)
        for _ in range(15):
            item = QListWidgetItem(type=0)
            item.setText(randstring())
            self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.treeWidget = QTreeWidget(self.dockWidgetContents)
        for _ in range(5):
            root = QTreeWidgetItem(type=0)
            root.setText(0, randstring())
            self.treeWidget.addTopLevelItem(root)
            for _ in range(15):
                item = QTreeWidgetItem(type=0)
                item.setText(0, randstring())
                root.addChild(item)
        # self.treeWidget.setHeaderItem()
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.tableWidget = QTableWidget(self.dockWidgetContents)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        for _ in range(15):
            rownum = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rownum)
            item1 = QTableWidgetItem(type=0)
            item2 = QTableWidgetItem(type=0)
            item1.setText(randstring())
            item2.setText(randstring())
            self.tableWidget.setItem(rownum, 0, item1)
            self.tableWidget.setItem(rownum, 1, item2)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.toolBox.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton.setObjectName("pushButton")
        self.radioButton.setObjectName("radioButton")
        self.checkBox.setObjectName("checkBox")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.toolButton.setObjectName("toolButton")
        self.buttonBox.setObjectName("buttonBox")
        self.toolBox.setObjectName("toolBox")
        self.page.setObjectName("page")
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit.setObjectName("lineEdit")
        self.timeEdit.setObjectName("timeEdit")
        self.fontComboBox.setObjectName("fontComboBox")
        self.comboBox.setObjectName("comboBox")
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit.setObjectName("textEdit")
        self.textBrowser.setObjectName("textBrowser")
        self.dial.setObjectName("dial")
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.calendarWidget.setObjectName("calendarWidget")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_5.setObjectName("page_5")
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line.setObjectName("line")
        self.verticalSlider.setObjectName("verticalSlider")
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.page_6.setObjectName("page_6")
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.line_2.setObjectName("line_2")
        self.progressBar.setObjectName("progressBar")
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget.setObjectName("listWidget")
        self.treeWidget.setObjectName(u"treeWidget")
        self.tableWidget.setObjectName(u"tableWidget")
