from typing import *
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from PySide6.QtGui import *

class Tab2(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.gridLayout_2 = QGridLayout()
        self.setLayout(self.gridLayout_2)
        self.pushButton = QPushButton(self.groupBox)
        self.toolButton = QToolButton(self.groupBox)
        self.radioButton = QRadioButton(self.groupBox)
        self.buttonBox = QDialogButtonBox(self.groupBox)
        self.commandLinkButton = QCommandLinkButton(self.groupBox)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.toolBox = QToolBox(self.tab_2)
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox_2 = QGroupBox(self.tab_2)
        self.checkBox = QCheckBox(self.groupBox)
        self.spinBox = QSpinBox(self.page_3)
        self.fontComboBox = QFontComboBox(self.page_3)
        self.doubleSpinBox = QDoubleSpinBox(self.page_3)
        self.comboBox = QComboBox(self.page_3)
        self.tableWidget = QTableWidget(self.tab_2)
        self.stackedWidget = QStackedWidget(self.tab_2)
        self.listWidget = QListWidget(self.tab_2)
        self.textBrowser = QTextBrowser(self.tab_2)
        self.page = QWidget()
        self.page.setGeometry(QRect(0, 0, 242, 145))
        self.page_2 = QWidget()
        self.page_2.setGeometry(QRect(0, 0, 249, 183))
        self.page_3 = QWidget()
        self.page_4 = QWidget()
        self.verticalScrollBar = QScrollBar(self.page)
        self.verticalScrollBar.setOrientation(Qt.Vertical)
        self.horizontalScrollBar = QScrollBar(self.page_2)
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.verticalSlider = QSlider(self.page)
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.horizontalSlider = QSlider(self.page_2)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.line = QFrame(self.page)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.page_2)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.dial = QDial(self.page_2)
        self.lcdNumber = QLCDNumber(self.page_4)
        self.progressBar = QProgressBar(self.page_2)
        self.progressBar.setValue(24)
        self.dateEdit = QDateEdit(self.page_4)
        self.dateTimeEdit = QDateTimeEdit(self.page_4)
        self.timeEdit = QTimeEdit(self.page_4)
        self.textEdit = QTextEdit(self.groupBox_2)
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.scrollArea = QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 260, 69))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.toolBox.addItem(self.page_2, u"Page 2")
        self.stackedWidget.addWidget(self.page_4)
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout_2 = QVBoxLayout(self.page_3)
        self.verticalLayout_3 = QVBoxLayout(self.page_2)
        self.verticalLayout_4 = QVBoxLayout(self.page_4)
        self.verticalLayout_5 = QVBoxLayout(self.groupBox_2)
        self.horizontalLayout = QHBoxLayout(self.central)
        self.horizontalLayout_2 = QHBoxLayout(self.page)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.treeWidget, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.textBrowser, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.toolBox, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.listWidget, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.toolButton)
        self.verticalLayout.addWidget(self.radioButton)
        self.verticalLayout.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.commandLinkButton)
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addWidget(self.fontComboBox)
        self.verticalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout_3.addWidget(self.horizontalScrollBar)
        self.verticalLayout_3.addWidget(self.dial)
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.horizontalSlider)
        self.verticalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout_4.addWidget(self.dateTimeEdit)
        self.verticalLayout_4.addWidget(self.timeEdit)
        self.verticalLayout_4.addWidget(self.lcdNumber)
        self.verticalLayout_5.addWidget(self.textEdit)
        self.verticalLayout_5.addWidget(self.plainTextEdit)
        self.horizontalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addWidget(self.verticalScrollBar)
        self.horizontalLayout_2.addWidget(self.line)
        self.horizontalLayout_2.addWidget(self.verticalSlider)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget.setObjectName("tabWidget")
        self.tab.setObjectName(u"tab")
        self.gridLayout.setObjectName(u"gridLayout")
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.pushButton.setObjectName(u"pushButton")
        self.toolButton.setObjectName(u"toolButton")
        self.radioButton.setObjectName(u"radioButton")
        self.checkBox.setObjectName(u"checkBox")
        self.commandLinkButton.setObjectName(u"commandLinkButton")
        self.buttonBox.setObjectName(u"buttonBox")
        self.tableWidget.setObjectName(u"tableWidget")
        self.treeWidget.setObjectName(u"treeWidget")
        self.textBrowser.setObjectName(u"textBrowser")
        self.toolBox.setObjectName(u"toolBox")
        self.page.setObjectName(u"page")
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.verticalScrollBar.setObjectName(u"verticalScrollBar")
        self.line.setObjectName(u"line")
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.toolBox.addItem(self.page, u"Page 1")
        self.page_2.setObjectName(u"page_2")
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.dial.setObjectName(u"dial")
        self.line_2.setObjectName(u"line_2")
        self.progressBar.setObjectName(u"progressBar")
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page_3.setObjectName(u"page_3")
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.fontComboBox.setObjectName(u"fontComboBox")
        self.spinBox.setObjectName(u"spinBox")
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.comboBox.setObjectName(u"comboBox")
        self.page_4.setObjectName(u"page_4")
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.timeEdit.setObjectName(u"timeEdit")
        self.lcdNumber.setObjectName(u"lcdNumber")
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.textEdit.setObjectName(u"textEdit")
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.listWidget.setObjectName(u"listWidget")
