import random
import string
from typing import *
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from PySide6.QtGui import *

def randstring():
    text = ""
    for _ in range(random.randint(8,35)):
        text += random.choice(string.printable)
    return text

class Tab2(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.grid = QGridLayout()
        self.setLayout(self.grid)
        self.pushButton = QPushButton("Push Button", self)
        self.radioButton = QRadioButton("Radio Button",self)
        self.checkBox = QCheckBox("Check Box", self)
        self.commandLinkButton = QCommandLinkButton("Command Link",self)
        self.toolButton = QToolButton(self)
        self.toolButton.setText("ToolButton")
        self.buttonBox = QDialogButtonBox(self)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.lineEdit = QLineEdit(self)
        self.timeEdit = QTimeEdit(self)
        self.fontComboBox = QFontComboBox(self)
        self.comboBox = QComboBox(self)
        self.spinBox = QSpinBox(self)
        self.doubleSpinBox = QDoubleSpinBox(self)
        self.textEdit = QTextEdit(self)
        self.textBrowser = QTextBrowser(self)
        self.dial = QDial(self)
        self.plainTextEdit = QPlainTextEdit(self)
        self.calendarWidget = QCalendarWidget(self)
        self.line = QFrame(self)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalSlider = QSlider(self)
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.lcdNumber = QLCDNumber(self)
        self.verticalScrollBar = QScrollBar(self)
        self.line2 = QFrame(self)
        self.line2.setFrameShape(QFrame.HLine)
        self.line2.setFrameShadow(QFrame.Sunken)
        self.verticalScrollBar.setOrientation(Qt.Vertical)
        self.horizontalScrollBar = QScrollBar(self)
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.horizontalSlider = QSlider(self)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.progressBar = QProgressBar(self)
        self.keySequenceEdit = QKeySequenceEdit(self)
        self.dockWidget = QDockWidget(self)
        self.listWidget = QListWidget(self)
        for _ in range(15):
            item = QListWidgetItem(type=0)
            item.setText(randstring())
            self.listWidget.addItem(item)
        self.treeWidget = QTreeWidget(self)
        for _ in range(5):
            root = QTreeWidgetItem(type=0)
            root.setText(0, randstring())
            self.treeWidget.addTopLevelItem(root)
            for _ in range(15):
                item = QTreeWidgetItem(type=0)
                item.setText(0, randstring())
                root.addChild(item)
        # self.treeWidget.setHeaderItem()
        self.tableWidget = QTableWidget(self)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        for _ in range(15):
            rownum = self.tableWidget.rowCount()
            self.tableWidget.insertRow(rownum)
            item1 = QTableWidgetItem(type=0)
            item2 = QTableWidgetItem(type=0)
            item1.setText(randstring())
            item2.setText(randstring())
            self.tableWidget.setItem(rownum, 0, item1)
            self.tableWidget.setItem(rownum, 1, item2)
        self.grid.addWidget(self.comboBox,0,0)
        self.grid.addWidget(self.fontComboBox,0,1)
        self.grid.addWidget(self.timeEdit,0,2)
        self.grid.addWidget(self.spinBox,0,3)
        self.grid.addWidget(self.doubleSpinBox,0,4)
        self.grid.addWidget(self.pushButton, 1, 0)
        self.grid.addWidget(self.radioButton, 1, 1)
        self.grid.addWidget(self.checkBox, 1,2)
        self.grid.addWidget(self.toolButton,1,3)
        self.grid.addWidget(self.buttonBox,1,4)
        self.grid.addWidget(self.lineEdit,2,0)
        self.grid.addWidget(self.commandLinkButton, 2,1)
        self.grid.addWidget(self.keySequenceEdit,2,2)
        self.grid.addWidget(self.lcdNumber,2,3)
        self.grid.addWidget(self.progressBar,2,4)
        self.grid.addWidget(self.horizontalScrollBar,3,0,1,2)
        self.grid.addWidget(self.horizontalSlider,3,2,1,2)
        self.grid.addWidget(self.line2,3,4)
        self.grid.addWidget(self.verticalSlider,4,4)
        self.grid.addWidget(self.verticalScrollBar,4,1)
        self.grid.addWidget(self.line,4,3)
        self.grid.addWidget(self.dial,4,2)
        self.grid.addWidget(self.textEdit,5,1)
        self.grid.addWidget(self.textBrowser,5,2)
        self.grid.addWidget(self.plainTextEdit,5,0)
        self.grid.addWidget(self.calendarWidget,6,1,1,2)
        self.grid.addWidget(self.dockWidget,6,0)
        self.grid.addWidget(self.listWidget,6,3)
        self.grid.addWidget(self.treeWidget,6,4)
        self.grid.addWidget(self.tableWidget,5,3,1,2)
