name: Coverage

on: [push, pull_request]
jobs:
  run:
    name: CI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Python Version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox PySide6
          pip install coverage pytest
      - name: Run Tests
        run: |
          coverage run -m pytest tests QStyler
          coverage xml -io ./coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
