name: Coverage

on: [push, pull_request]
jobs:
  run:
    name: CI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
      - name: Display Python Version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox PySide6
          pip install coverage pytest pytest-cov

      - name: Run Tests
        run: |
          tox
          pytest --cov=QStyler --cov=tests
          coverage report
          coverage xml -o coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
          flags: unittests
          fail_ci_if_error: true
