name: UbuntuCI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: ${{ matrix.python-version  }}
      - name: Display Python Version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          tox
