name: CI

on: [push, pull_request]
jobs:
  run:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display Python Version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox torrentfile PySide6
      - name: Run Tests
        run: |
          tox
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage.xml
          verbose: true

      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.1.0
        with:
          coverage-reports: ./coverage.xml
